from enum import Enum


class FavoriteItemException(Enum):
    FAVORITE_ITEM_NOT_FOUND = "FAVORITE ITEM NOT FOUND"
    FAVORITE_ITEM_ALREADY_EXISTS = "FAVORITE ITEM ALREADY EXISTS"
    SOMTHING_WENT_WRONG = "SOMTHING WENT WRONG"