from enum import Enum


class FavoriteItemException(Enum):
    FAVORITE_ITEM_NOT_FOUND = "FAVORITE ITEM NOT FOUND"
    ITEM_NOT_FOUND = "ITEM NOT FOUND"
    ITEM_NOT_IN_FAVORITES = "ITEM NOT IN FAVORITES"
    FAVORITE_ITEM_ALREADY_EXISTS = "FAVORITE ITEM ALREADY EXISTS"
    SOMTHING_WENT_WRONG = "SOMTHING WENT WRONG"
